### ISSUE TITLE
pycparser.ply.yacc.YaccError: Unable to build parser

### ISSUE THREAD

**Issue by githubg0** [inducer/pycparserext#43] opened 2019-07-07 13:39 UTC
dear author, I encountered a error

>  p = GnuCParser()
  File "/usr/local/lib/python3.6/dist-packages/pycparserext/ext_c_parser.py", line 47, in __init__
    debug=yacc_debug, write_tables=False)
  File "/home/longting/.local/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 3426, in yacc
    raise YaccError('Unable to build parser')
pycparser.ply.yacc.YaccError: Unable to build parser

 when I use the example you gave in test. my code as following:

> def test_asm_volatile_2(src):
    from pycparserext.ext_c_parser import GnuCParser
    p = GnuCParser()
    ast = p.parse(src)
    ast.show()
    from pycparserext.ext_c_generator import GnuCGenerator
    print(GnuCGenerator().visit(ast))

> src=open('880.cpp','r').read()
   test_asm_volatile_2(src)

in which src is a cpp code 
could you please give me some advice.

**Comment by inducer** [comment] 2019-07-07 19:14
I can't reproduce your issue. Also, the tests get run [weekly](https://gitlab.tiker.net/inducer/pycparserext/commit/4e3d549a9d2b64f16ed9af32fdfe60d1c9c7d799/pipelines) against current versions of ply and pycparserext.

**Comment by githubg0** [comment] 2019-07-08 03:46
the '880.cpp' as  follow:

> int main()
{
	int N;
	cin>>N;
	int i,b=0,count=1,sum=0;	
	for(i=0;i<N;i++)
	cin>>p[i];
	for(i=0;i<N;i++)
	{
		if(b<0)
			{b=p[i];count=1;}
		else
		{
			b+=p[i];count++;	
		}	
		if(b>sum&&count>1)
				sum=b;			
	}
	if(sum>0)
	cout<<sum<<endl;
	else
	cout<<"Game Over"<<endl; 	
}

**Comment by inducer** [comment] 2019-07-08 14:03
An error like
```
pycparser.ply.yacc.YaccError: Unable to build parser
```
occurs *before* any actual source code gets looked at.

**Comment by belyak** [comment] 2019-07-14 09:42
I have the same problem. How to reproduce:
`
python3.6 -m venv venv
source venv/bin/activate
pip install pycparserext
`
then run `python3` and try to create parser:
`
(venv) andy@andy-ThinkPad-E490:~$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycparserext.ext_c_parser import GnuCParser
>>> parser = GnuCParser()
ERROR: /home/andy/venv/lib/python3.6/site-packages/pycparser/c_parser.py:683: Symbol 'id_init_declarator_list_opt' used, but not defined as a token or a rule
ERROR: /home/andy/venv/lib/python3.6/site-packages/pycparser/c_parser.py:762: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
ERROR: /home/andy/venv/lib/python3.6/site-packages/pycparser/c_parser.py:767: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
ERROR: /home/andy/venv/lib/python3.6/site-packages/pycparser/c_parser.py:772: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
WARNING: /home/andy/venv/lib/python3.6/site-packages/pycparser/plyparser.py:43: Rule 'declaration_specifiers_opt' defined, but not used
WARNING: /home/andy/venv/lib/python3.6/site-packages/pycparser/plyparser.py:43: Rule 'specifier_qualifier_list_opt' defined, but not used
WARNING: There are 2 unused rules
WARNING: Symbol 'declaration_specifiers_opt' is unreachable
WARNING: Symbol 'specifier_qualifier_list_opt' is unreachable
WARNING: Symbol 'id_init_declarator_list' is unreachable
WARNING: Symbol 'id_init_declarator' is unreachable
ERROR: Infinite recursion detected for symbol 'direct_declarator'
ERROR: Infinite recursion detected for symbol 'declaration_specifiers_no_type'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andy/venv/lib/python3.6/site-packages/pycparserext/ext_c_parser.py", line 47, in __init__
    debug=yacc_debug, write_tables=False)
  File "/home/andy/venv/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 3426, in yacc
    raise YaccError('Unable to build parser')
pycparser.ply.yacc.YaccError: Unable to build parser
`

**Comment by inducer** [comment] 2019-07-14 16:15
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycparserext.ext_c_parser import GnuCParser
>>> parser = GnuCParser()
>>> import pycparser
>>> pycparser.__version__
'2.19'
>>>
```
2.19 is current AFAICT. I guess you're installing for the package index, which is ancient (2016-ish). I've just uploaded a new release. Let me know if that works for you.

**Comment by belyak** [comment] 2019-07-15 05:46
> ```
> Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from pycparserext.ext_c_parser import GnuCParser
> >>> parser = GnuCParser()
> >>> import pycparser
> >>> pycparser.__version__
> '2.19'
> >>>
> ```
> 
> 2.19 is current AFAICT. I guess you're installing for the package index, which is ancient (2016-ish). I've just uploaded a new release. Let me know if that works for you.

Now it works (version was 2016.2 yesterday, now it is 2019.1).
Thank you!

**Comment by inducer** [comment] 2019-07-15 15:31
Thanks, closing.

**Closed by inducer** 2019-07-15 15:31 UTC

**Comment by jhlee838** [comment] 2020-04-19 05:10
.
